ARG ARG_RUBY_VERSION

# "Debian GNU/Linux 10 (buster)"
FROM ruby:${ARG_RUBY_VERSION}

ENV LANG C.UTF-8

RUN  apt-get update -qq && \
  apt-get install -y apt-utils

RUN apt-get install -y build-essential \
  libpq-dev \
  && rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]

ENV APP_PATH src

ENV BUNDLE_WITHOUT production
ENV BUNDLE_JOBS 3
ENV BUNDLE_RETRY 3

WORKDIR /${APP_PATH}

COPY . /${APP_PATH}

RUN gem update --system

RUN bundle config set --local deployment 'true'
RUN bundler install --local

RUN cp -f config/database-ci.yml config/database.yml

RUN cp -f config/environments/test-ci.rb config/environments/test.rb

CMD [ "echo", "CI Container [$RUBYGEMS_VERSION]" ]
