name: Tests

on: [push]

env:
  CI: true
  RAILS_ENV: test

jobs:

  check:

    runs-on: ubuntu-latest

    outputs:
      branch: ${{ steps.branch-commits.outputs.branch }}
      sha: ${{ steps.branch-commits.outputs.sha_short }}

    steps:
      -
        name: Check Out Code
        uses: actions/checkout@v3

      -
        name: Get Current Branch and Commit
        id: branch-commits
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      -
        name: Show Current Branch and Commit
        run: |
          echo "Branch: ${{ steps.branch-commits.outputs.branch }}"
          echo "Sha: ${{ steps.branch-commits.outputs.sha_short }}"

      -
        name: Setup Ruby 3.1.1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1.1'

      -
        name: Setup configuration
        run: |
          cp -f config/database-ci.yml config/database.yml
          cp -f config/environments/test-ci.rb config/environments/test.rb

      -
        name: Run Tests
        run: PARALLEL_WORKERS=4 bin/rails test

      -
        name: Run Linter
        run: bundle exec rubocop --parallel
